/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/room12.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Room12(props) {
  const { nodes, materials } = useGLTF('/models/room12.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Node1.geometry} material={materials.Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Node2.geometry} material={materials.CushionBrown} />
      <mesh castShadow receiveShadow geometry={nodes.Node3.geometry} material={materials.TatamiGreen} />
      <mesh castShadow receiveShadow geometry={nodes.Node7.geometry} material={materials.TeaPotWhite} />
      <mesh castShadow receiveShadow geometry={nodes.Node13.geometry} material={materials.TableVaseGray} />
      <mesh castShadow receiveShadow geometry={nodes.Node14.geometry} material={materials.Black} />
      <mesh castShadow receiveShadow geometry={nodes.Node15.geometry} material={materials.Black} />
      <mesh castShadow receiveShadow geometry={nodes.Node16.geometry} material={materials.Black} />
      <mesh castShadow receiveShadow geometry={nodes.Node17.geometry} material={materials.Black} />
      <mesh castShadow receiveShadow geometry={nodes.Node18.geometry} material={materials.DarkerWood} />
      <mesh castShadow receiveShadow geometry={nodes.Node19.geometry} material={materials.TeaPotWhite} />
      <mesh castShadow receiveShadow geometry={nodes.Node20.geometry} material={materials.TeaPotWhite} />
      <mesh castShadow receiveShadow geometry={nodes.Node21.geometry} material={materials.WoodDark} />
      <mesh castShadow receiveShadow geometry={nodes.Node22.geometry} material={materials.WoodDark} />
      <mesh castShadow receiveShadow geometry={nodes.Node24.geometry} material={materials.Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_3.geometry} material={materials.CupInnerRed} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_4.geometry} material={materials.CupOuterPurple} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_5.geometry} material={materials.CupInnerRed} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_6.geometry} material={materials.CupOuterBeige} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_7.geometry} material={materials.CupOuterPink} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_8.geometry} material={materials.CupInnerPurple} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_9.geometry} material={materials.CupOuterGold} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_11.geometry} material={materials.Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_12.geometry} material={materials.TatamiGreen} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_13.geometry} material={materials.TatamiGreen} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_14.geometry} material={materials.ShelfTopDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_15.geometry} material={materials.Lamp} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_16.geometry} material={materials.Black} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_17.geometry} material={materials.Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_18.geometry} material={materials.Black} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_19.geometry} material={materials.Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_20.geometry} material={materials.Black} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_31.geometry} material={materials.Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_32.geometry} material={materials.WindowWhite} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_34.geometry} material={materials.Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_35.geometry} material={materials.TatamiGreen} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_36.geometry} material={materials.TatamiGreen} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_37.geometry} material={materials.WallLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_38.geometry} material={materials.Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_39.geometry} material={materials.TatamiGreen} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh0_40.geometry} material={materials.FloorWhite} />
    </group>
  )
}

useGLTF.preload('/models/room12.gltf')
