/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Room(props) {
  const { nodes, materials } = useGLTF('/models/room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Walls.geometry} material={materials.walls} position={[-0.631, 2.109, -0.86]} />
      <mesh geometry={nodes.Floor.geometry} material={materials.floor} position={[0, 0.15, 0]} />
      <mesh geometry={nodes.Walls001.geometry} material={materials.Material} position={[0.442, 3.136, -0.258]} scale={1.938} />
      <group position={[-0.787, 1.222, -1.265]} scale={0.836}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.cupboard} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Mirror} />
      </group>
      <mesh geometry={nodes.cupboard_handles.geometry} material={materials.Cupboard_handles} position={[-0.747, 1.202, -1.031]} scale={[0.02, 0.108, 0.014]} />
      <group position={[1.012, 1.375, -1.388]} rotation={[Math.PI / 2, 0, 0]} scale={1.083}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Mouse} />
      </group>
      <mesh geometry={nodes.shelf_handles.geometry} material={materials.Cupboard_handles} position={[1.007, 1.222, -1.229]} scale={[0.022, 0.108, 0.014]} />
      <group position={[0.394, 1.314, -1.284]} rotation={[0, 0.466, 0]} scale={[0.059, 0.008, 0.111]}>
        <mesh geometry={nodes.Cube016.geometry} material={materials.bed} />
        <mesh geometry={nodes.Cube016_1.geometry} material={materials.Computer_screen} />
      </group>
      <mesh geometry={nodes.Coffee_cup.geometry} material={materials.bed} position={[1.555, 1.298, -1.212]} scale={[0.044, 0.076, 0.044]} />
      <mesh geometry={nodes.computer_stand.geometry} material={materials.Mouse} position={[1.007, 1.311, -1.228]} scale={[-0.117, -0.008, -0.117]} />
      <group position={[1.095, 1.588, -1.209]} scale={1.315}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.Mouse} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.Computer_screen} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.computer_light} />
      </group>
      <mesh geometry={nodes.keyboard.geometry} material={materials.Mouse} position={[1.018, 1.302, -0.936]} />
      <group position={[1.478, 1.314, -0.972]} scale={[-0.035, -0.025, -0.08]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials.Mouse} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.mouse_scroller} />
      </group>
      <mesh geometry={nodes.Curve006.geometry} material={materials.Netflix} position={[1.028, 1.794, -1.207]} rotation={[Math.PI / 2, 0, 0]} scale={1.354} />
      <mesh geometry={nodes.Curve.geometry} material={materials.Netflix} position={[1.011, 1.557, -1.207]} rotation={[Math.PI / 2, 0, 0]} scale={1.895} />
      <group position={[1.64, 1.818, -1.508]} rotation={[0, 1.522, 0]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials.modem} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.modem_light} />
      </group>
      <group position={[-1.312, 3.386, -1.429]} scale={0.853}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Mouse} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.computer_light} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.mouse_scroller} />
      </group>
      <group position={[-0.358, 3.386, -1.429]} scale={0.853}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Mouse} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.computer_light} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.mouse_scroller} />
      </group>
      <mesh geometry={nodes.Wire.geometry} material={materials.Mouse} position={[-0.726, 2.802, -1.694]} scale={[-0.009, -0.019, -0.009]} />
      <mesh geometry={nodes.chandelier_stand.geometry} material={materials.floor} position={[0, 3.949, 0]} scale={[0.518, 0.211, 0.13]} />
      <mesh geometry={nodes.chandeliers.geometry} material={materials.window_frame} position={[-0.002, 3.296, -0.054]} scale={[0.133, 0.175, 0.133]} />
      <mesh geometry={nodes.chandelier_rod.geometry} material={materials.Mouse} position={[0.012, 3.687, -0.054]} scale={[-0.007, -0.085, -0.007]} />
      <mesh geometry={nodes.chandelier_bulb.geometry} material={nodes.chandelier_bulb.material} position={[0.012, 2.989, -0.049]} scale={0.052} />
      <group position={[0.998, 2.82, -1.585]} rotation={[Math.PI / 2, 0, 0]} scale={[1.132, 1, 0.826]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.curtain} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials.curtain} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.curtain} />
      </group>
      <mesh geometry={nodes.curtain_railing_1.geometry} material={materials.curtain_railings} position={[0.994, 3.772, -1.63]} scale={[1.118, 1, 1]} />
      <mesh geometry={nodes.curtain_loops_1.geometry} material={materials.curtain_railings} position={[1.555, 3.756, -1.584]} rotation={[Math.PI / 2, 0, 0]} scale={[0.011, 0.01, 0.01]} />
      <group position={[-1.61, 2.183, 0.005]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.765, 1, 1.402]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials.curtain} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.curtain} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials.curtain} />
      </group>
      <mesh geometry={nodes.curtain_railing_1001.geometry} material={materials.curtain_railings} position={[-1.657, 3.772, 0.729]} rotation={[0, 1.571, 0]} scale={[1.118, 1, 1]} />
      <mesh geometry={nodes.curtain_loops_1001.geometry} material={materials.curtain_railings} position={[-1.612, 3.756, -0.376]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.011, 0.01, 0.01]} />
      <mesh geometry={nodes.lamp.geometry} material={materials.lamp} position={[-1.531, 3.39, -0.752]} scale={[0.163, 0.253, 0.163]} />
      <mesh geometry={nodes.lamp_handle.geometry} material={materials.lamp_handle} position={[-1.66, 3.135, -0.75]} scale={[0.025, 0.153, 0.051]} />
      <mesh geometry={nodes.bed.geometry} material={materials.bed} position={[-0.691, 0.956, 1.398]} />
      <mesh geometry={nodes.pillows.geometry} material={materials.cushion} position={[-0.3, 1.136, 1.613]} rotation={[3.065, 0, 0]} scale={[0.274, 0.008, 0.244]} />
      <mesh geometry={nodes.bed_stands.geometry} material={materials.Mouse} position={[-0.686, 0.358, 0.736]} scale={[-0.03, -0.058, -0.03]} />
      <mesh geometry={nodes.bedsheet.geometry} material={materials.bedsheet} position={[-0.643, 0.899, 0.72]} rotation={[-0.702, 0, 0]} scale={[1.091, 1, 0.989]} />
      <mesh geometry={nodes.matress.geometry} material={materials.bedsheet} position={[-0.687, 0.844, 0.699]} scale={[0.657, 0.101, 1.008]} />
      <mesh geometry={nodes.pillows001.geometry} material={materials.cushion} position={[-0.479, 1.091, 0.671]} rotation={[3.065, 0, 0]} scale={[0.274, 0.008, 0.244]} />
      <mesh geometry={nodes.pillows002.geometry} material={materials.cushion} position={[-0.942, 1.11, 1.504]} rotation={[3.065, 0, 0]} scale={[0.274, 0.008, 0.244]} />
      <group position={[0.448, 1.706, -1.497]} scale={[1.108, 1.325, 1.108]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials.book} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.modem} />
      </group>
      <group position={[0.448, 1.74, -1.496]} rotation={[0, -0.413, 0]} scale={[1.108, 1.325, 1.108]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.book} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.modem} />
      </group>
      <group position={[0.448, 1.774, -1.497]} rotation={[0, 0.159, 0]} scale={[1.108, 1.325, 1.108]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.book} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.modem} />
      </group>
      <group position={[0.987, 2.828, -1.706]} scale={[1, 0.887, 1]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.window_frame} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Window_emission} />
      </group>
      <group position={[-1.881, 2.159, 0.735]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials.window_frame} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials.Window_emission} />
      </group>
      <group position={[1.365, 0.502, 1.243]} rotation={[-0.08, -0.327, -0.026]} scale={0.408}>
        <mesh geometry={nodes.Plane004.geometry} material={materials.puffy_chair} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.puffy_chair} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials.puffy_chair} />
        <mesh geometry={nodes.Plane004_3.geometry} material={materials.puffy_chair} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/room.glb')
